#-------------------------------------------------------------------------------
# Name:        module1
# Purpose:
#
# Author:      Geekman2
#
# Created:     22/10/2012
# Copyright:   (c) Geekman2 2012
# Licence:     <your licence>
#-------------------------------------------------------------------------------
from Tkinter import *
from rox import*
from Makefile import*
from random import*
from PIL import*
Characters = [Percy,Annabeth,Chuck,Leo,Sarah,Piper,Jason,Morgan,Hazel,Shawn,Casey]
shuffle(Characters)
count = 0
class App:
    def __init__(self, master):
        print master
        def callback(event):

            C = Characters.pop(0)
            event.grid_forget()
            return C()


        def crepe():
            char = raw_input('Character:')
            quo = raw_input('Quote:')
            makewindow(char,quo)
            Characters.append(char)
        def hide_me(event):
            event.widget.grid_forget()





        la=Label(master,text='The Rock Game')
        la.grid(row=0,column=3)
        Button1=Button(master,text='click me',command=lambda:callback(Button1))
        Button1.grid(row=1,column=1)
        Button2=Button(master,text='click me',command=lambda:callback(Button2))
        Button2.grid(row=1,column=2)
        Button3=Button(master,text='click me',command=lambda:callback(Button3))
        Button3.grid(row=1,column=3)
        Button4=Button(master,text='click me',command=lambda:callback(Button4))
        Button4.grid(row=1,column=4)
        Button5=Button(master,text='click me',command=lambda:callback(Button5))
        Button5.grid(row=1,column=5)
        Button6=Button(master,text='click me',command=lambda:callback(Button6))
        Button6.grid(row=1,column=6)
        Button7=Button(master,text='click me',command=lambda:callback(Button7))
        Button7.grid(row=2,column=1)
        Button8=Button(master,text='click me',command=lambda:callback(Button8))
        Button8.grid(row=2,column=2)
        Button9=Button(master,text='click me',command=lambda:callback(Button9))
        Button9.grid(row=2,column=3)
        Button10=Button(master,text='click me',command=lambda:callback(Button10))
        Button10.grid(row=2,column=4)
        Button11=Button(master,text='click me',command=lambda:callback(Button11))
        Button11.grid(row=2,column=5)
        Button12=Button(master,text='click me',command=lambda:callback(Button12))
        Button12.grid(row=2,column=6)
        Button13=Button(master,text='click me',command=lambda:callback(Button13))
        Button13.grid(row=3,column=1)
        Button14=Button(master,text='click me',command=lambda:callback(Button14))
        Button14.grid(row=3,column=2)
        Button15=Button(master,text='click me',command=lambda:callback(Button15))
        Button15.grid(row=3,column=3)
        Button16=Button(master,text='click me',command=lambda:callback(Button16))
        Button16.grid(row=3,column=4)
        Button17=Button(master,text='click me',command=lambda:callback(Button17))
        Button17.grid(row=3,column=5)
        Button18=Button(master,text='click me',command=lambda:callback(Button18))
        Button18.grid(row=3,column=6)
        Button19=Button(master,text='click me',command=lambda:callback(Button19))
        Button19.grid(row=4,column=1)
        Button20=Button(master,text='click me',command=lambda:callback(Button20))
        Button20.grid(row=4,column=2)
        Button21=Button(master,text='click me',command=lambda:callback(Button21))
        Button21.grid(row=4,column=3)
        Button22=Button(master,text='click me',command=lambda:callback(Button22))
        Button22.grid(row=4,column=4)
        Button23=Button(master,text='click me',command=lambda:callback(Button23))
        Button23.grid(row=4,column=5)
        Button24=Button(master,text='click me',command=lambda:callback(Button24))
        Button24.grid(row=4,column=6)
        Button25=Button(master,text='click me',command=lambda:callback(Button25))
        Button25.grid(row=5,column=1)
        Button26=Button(master,text='click me',command=lambda:callback(Button26))
        Button26.grid(row=5,column=2)
        Button27=Button(master,text='click me',command=lambda:callback(Button27))
        Button27.grid(row=5,column=3)
        Button28=Button(master,text='click me',command=lambda:callback(Button28))
        Button28.grid(row=5,column=4)
        Button29=Button(master,text='click me',command=lambda:callback(Button29))
        Button29.grid(row=5,column=5)
        Button30=Button(master,text='click me',command=lambda:callback(Button30))
        Button30.grid(row=5,column=6)
        Button31=Button(master,text='click me',command=lambda:callback(Button31))
        Button31.grid(row=6,column=1)
        Button32=Button(master,text='click me',command=lambda:callback(Button32))
        Button32.grid(row=6,column=2)
        Button33=Button(master,text='click me',command=lambda:callback(Button33))
        Button33.grid(row=6,column=3)
        Button34=Button(master,text='click me',command=lambda:callback(Button34))
        Button34.grid(row=6,column=4)
        Button35=Button(master,text='click me',command=lambda:callback(Button35))
        Button35.grid(row=6,column=5)
        Button36=Button(master,text='click me',command=lambda:callback(Button36))
        Button36.grid(row=6,column=6)
        Button37=Button(master,text='click me',command=lambda:callback(Button37))
        Button37.grid(row=7,column=1)
        Button38=Button(master,text='click me',command=lambda:callback(Button38))
        Button38.grid(row=7,column=2)
        Button39=Button(master,text='click me',command=lambda:callback(Button39))
        Button39.grid(row=7,column=3)
        Button40=Button(master,text='click me',command=lambda:callback(Button40))
        Button40.grid(row=7,column=4)
        Button41=Button(master,text='click me',command=lambda:callback(Button41))
        Button41.grid(row=7,column=5)
        Button42=Button(master,text='click me',command=lambda:callback(Button42))
        Button42.grid(row=7,column=6)
        Button43=Button(master,text='click me',command=lambda:callback(Button43))
        Button43.grid(row=8,column=1)
        Button44=Button(master,text='click me',command=lambda:callback(Button44))
        Button44.grid(row=8,column=2)
        Button45=Button(master,text='click me',command=lambda:callback(Button45))
        Button45.grid(row=8,column=3)
        Button46=Button(master,text='click me',command=lambda:callback(Button46))
        Button46.grid(row=8,column=4)
        Button47=Button(master,text='click me',command=lambda:callback(Button47))
        Button47.grid(row=8,column=5)
        Button48=Button(master,text='click me',command=lambda:callback(Button48))
        Button48.grid(row=8,column=6)
        Button49=Button(master,text='click me',command=lambda:callback(Button49))
        Button49.grid(row=9,column=1)
        Button50=Button(master,text='click me',command=lambda:callback(Button50))
        Button50.grid(row=9,column=2)
        Button51=Button(master,text='click me',command=lambda:callback(Button51))
        Button51.grid(row=9,column=3)
        Button52=Button(master,text='click me',command=lambda:callback(Button52))
        Button52.grid(row=9,column=4)
        Button53=Button(master,text='click me',command=lambda:callback(Button53))
        Button53.grid(row=9,column=5)
        Button54=Button(master,text='click me',command=lambda:callback(Button54))
        Button54.grid(row=9,column=6)
        Button55=Button(master,text='click me',command=lambda:callback(Button55))
        Button55.grid(row=10,column=1)
        Button56=Button(master,text='click me',command=lambda:callback(Button56))
        Button56.grid(row=10,column=2)
        Button57=Button(master,text='click me',command=lambda:callback(Button57))
        Button57.grid(row=10,column=3)
        Button58=Button(master,text='click me',command=lambda:callback(Button58))
        Button58.grid(row=10,column=4)
        Button59=Button(master,text='click me',command=lambda:callback(Button59))
        Button59.grid(row=10,column=5)
        Button60=Button(master,text='click me',command=lambda:callback(Button60))
        Button60.grid(row=10,column=6)
        Button61=Button(master,text='click me',command=lambda:callback(Button61))
        Button61.grid(row=11,column=1)
        Button62=Button(master,text='click me',command=lambda:callback(Button62))
        Button62.grid(row=11,column=2)
        Button63=Button(master,text='click me',command=lambda:callback(Button63))
        Button63.grid(row=11,column=3)
        Button64=Button(master,text='click me',command=lambda:callback(Button64))
        Button64.grid(row=11,column=4)
        Button65=Button(master,text='click me',command=lambda:callback(Button65))
        Button65.grid(row=11,column=5)
        Button66=Button(master,text='click me',command=lambda:callback(Button66))
        Button66.grid(row=11,column=6)
        Button67=Button(master,text='click me',command=lambda:callback(Button67))
        Button67.grid(row=12,column=1)
        Button68=Button(master,text='click me',command=lambda:callback(Button68))
        Button68.grid(row=12,column=2)
        Button69=Button(master,text='click me',command=lambda:callback(Button69))
        Button69.grid(row=12,column=3)
        Button70=Button(master,text='click me',command=lambda:callback(Button70))
        Button70.grid(row=12,column=4)
        Button71=Button(master,text='click me',command=lambda:callback(Button71))
        Button71.grid(row=12,column=5)
        Button72=Button(master,text='click me',command=lambda:callback(Button72))
        Button72.grid(row=12,column=6)
        Button73=Button(master,text='click me',command=lambda:callback(Button73))
        Button73.grid(row=13,column=1)
        Button74=Button(master,text='click me',command=lambda:callback(Button74))
        Button74.grid(row=13,column=2)
        Button75=Button(master,text='click me',command=lambda:callback(Button75))
        Button75.grid(row=13,column=3)
        Button76=Button(master,text='click me',command=lambda:callback(Button76))
        Button76.grid(row=13,column=4)
        Button77=Button(master,text='click me',command=lambda:callback(Button77))
        Button77.grid(row=13,column=5)
        Button78=Button(master,text='click me',command=lambda:callback(Button78))
        Button78.grid(row=13,column=6)
        Button79=Button(master,text='click me',command=lambda:callback(Button79))
        Button79.grid(row=14,column=1)
        Button80=Button(master,text='click me',command=lambda:callback(Button80))
        Button80.grid(row=14,column=2)
        Button81=Button(master,text='click me',command=lambda:callback(Button81))
        Button81.grid(row=14,column=3)
        Button82=Button(master,text='click me',command=lambda:callback(Button82))
        Button82.grid(row=14,column=4)
        Button83=Button(master,text='click me',command=lambda:callback(Button83))
        Button83.grid(row=14,column=5)
        Button84=Button(master,text='click me',command=lambda:callback(Button84))
        Button84.grid(row=14,column=6)
        Button85=Button(master,text='click me',command=lambda:callback(Button85))
        Button85.grid(row=15,column=1)
        Button86=Button(master,text='click me',command=lambda:callback(Button86))
        Button86.grid(row=15,column=2)
        Button87=Button(master,text='click me',command=lambda:callback(Button87))
        Button87.grid(row=15,column=3)
        Button88=Button(master,text='click me',command=lambda:callback(Button88))
        Button88.grid(row=15,column=4)
        Button89=Button(master,text='click me',command=lambda:callback(Button89))
        Button89.grid(row=15,column=5)
        Button90=Button(master,text='click me',command=lambda:callback(Button90))
        Button90.grid(row=15,column=6)
        Button91=Button(master,text='click me',command=lambda:callback(Button91))
        Button91.grid(row=16,column=1)
        Button92=Button(master,text='click me',command=lambda:callback(Button92))
        Button92.grid(row=16,column=2)
        Button93=Button(master,text='click me',command=lambda:callback(Button93))
        Button93.grid(row=16,column=3)
        Button94=Button(master,text='click me',command=lambda:callback(Button94))
        Button94.grid(row=16,column=4)
        Button95=Button(master,text='click me',command=lambda:callback(Button95))
        Button95.grid(row=16,column=5)
        Button96=Button(master,text='click me',command=lambda:callback(Button96))
        Button96.grid(row=16,column=6)
        Button97=Button(master,text='click me',command=lambda:callback(Button97))
        Button97.grid(row=17,column=1)
        Button98=Button(master,text='click me',command=lambda:callback(Button98))
        Button98.grid(row=17,column=2)
        Button99=Button(master,text='click me',command=lambda:callback(Button99))
        Button99.grid(row=17,column=3)



        makenew = Button(master,text='Create New Character',command=lambda: crepe())
        makenew.grid(column=3)



Admin = Tk()
Admin.geometry('+700+100')
app = App(Admin)
Admin.mainloop()

