#-------------------------------------------------------------------------------
# Name:        module1
# Purpose:
#
# Author:      Geekman2
#
# Created:     22/10/2012
# Copyright:   (c) Geekman2 2012
# Licence:     <your licence>
#-------------------------------------------------------------------------------
from Tkinter import *
from rox2 import*
from Makefile import*
from random import*
from PIL import*
diomg = [Billy,Bonnie,Ashley,Walter,Sapphira,Elam,Shiloh,Gabriel,Acacia]
diomb = [Morgan_le__faye,Devin,Arramos]
chuckg = [Chuck,Sarah,Awesome,Ellie,Casey,Alex,Orion,Bryce,Morgan]
chuckb = [Shaw,Shaw,Shaw,Rourke,Jill,Jeffster,Frost,Shaw,Tang,Emmet]
pjog = [Percy,Annabeth,Leo,Piper,Hazel,Jason,Frank,Grover]
pjob = [Luke,Clarisse,Octavian,Thalia]
dk = [Kale,Bardon,Dibl,Gymn,Fenworth,Librettowit,Dar,Regidor,Gilda,Risto,Stox]
psych =[Shawn,Juliet,Lassiter,Gus,Mcnab,Henry]
RA = [Will,Alyss,Horace,Halt,Evanlyn,Erak,Gilan,Morgarath,Oberjarl_Ragnak]
LOZ = [Link,Zelda,Fi,Farore,Din,Nayru,Ganon,Ganondorf,Fierce_Deity,Saria,Malon,Ghirahim,Groose]
other=[SO,Squirrels,Owls,Dantes,Guru_Guru,Gummy]
#KCG=[Sunny,Brandon,Smokey,Dallas,Stacy,Tanner,Megan,Bracken]
KCB=[]
CharactersA = [other]
shuffle(CharactersA)
shuffle(diomg)
shuffle(diomb)
shuffle(chuckg)
shuffle(chuckb)
shuffle(pjog)
shuffle(pjob)
shuffle(dk)
shuffle(psych)
shuffle(RA)
shuffle(LOZ)

count = 0

class App:

    def __init__(self, master):
        print master
        def Youare(wendow):
            You_are= Toplevel()
            You_are.geometry('+650+100')
            Button1=Button(You_are,text='Click here to find out',command=lambda:destroy(wendow))
            Button1.pack(side=BOTTOM)
            says = Label(You_are,text ='You are....',font=('Helvetica',74))
            says.pack(side=TOP)

        def destroy(wondow):
            wondow()
        def callback(event):
            whichlist=choice(CharactersA)
            listdex=CharactersA.index(whichlist)
            #print str(listdex)
            #print CharactersA
            if  len(CharactersA)==1 and len(whichlist)==1:
                   C=whichlist.pop(0)
                   Youare(C)
            elif len(whichlist)==0:
                   CharactersA.pop(listdex)

            else:
                C=whichlist.pop(0)
                event.grid_forget()
                return C()


        def crepe():

            again = 'y'
            #char = raw_input('Character:')
            #quo = raw_input('Quote:')
            while again=='y':
                char=raw_input('Character')
                quo=raw_input('Quote')
                makewindow(char,quo)
                again=(raw_input('Again?y/n :'))
        def hide_me(event):
            event.widget.grid_forget()





        la=Label(master,text='The Rock Game')
        la.grid(row=0,column=4)
        makenew = Button(master,text='Create New Character',command=lambda: crepe())
        makenew.grid(row=16,column=4)
        Button1=Button(master,text='click me',command=lambda:callback(Button1))
        Button1.grid(row=1,column=1)
        Button2=Button(master,text='click me',command=lambda:callback(Button2))
        Button2.grid(row=1,column=2)
        Button3=Button(master,text='click me',command=lambda:callback(Button3))
        Button3.grid(row=1,column=3)
        Button4=Button(master,text='click me',command=lambda:callback(Button4))
        Button4.grid(row=1,column=4)
        Button5=Button(master,text='click me',command=lambda:callback(Button5))
        Button5.grid(row=1,column=5)
        Button6=Button(master,text='click me',command=lambda:callback(Button6))
        Button6.grid(row=1,column=6)
        Button7=Button(master,text='click me',command=lambda:callback(Button7))
        Button7.grid(row=1,column=7)
        Button8=Button(master,text='click me',command=lambda:callback(Button8))
        Button8.grid(row=2,column=1)
        Button9=Button(master,text='click me',command=lambda:callback(Button9))
        Button9.grid(row=2,column=2)
        Button10=Button(master,text='click me',command=lambda:callback(Button10))
        Button10.grid(row=2,column=3)
        Button11=Button(master,text='click me',command=lambda:callback(Button11))
        Button11.grid(row=2,column=4)
        Button12=Button(master,text='click me',command=lambda:callback(Button12))
        Button12.grid(row=2,column=5)
        Button13=Button(master,text='click me',command=lambda:callback(Button13))
        Button13.grid(row=2,column=6)
        Button14=Button(master,text='click me',command=lambda:callback(Button14))
        Button14.grid(row=2,column=7)
        Button15=Button(master,text='click me',command=lambda:callback(Button15))
        Button15.grid(row=3,column=1)
        Button16=Button(master,text='click me',command=lambda:callback(Button16))
        Button16.grid(row=3,column=2)
        Button17=Button(master,text='click me',command=lambda:callback(Button17))
        Button17.grid(row=3,column=3)
        Button18=Button(master,text='click me',command=lambda:callback(Button18))
        Button18.grid(row=3,column=4)
        Button19=Button(master,text='click me',command=lambda:callback(Button19))
        Button19.grid(row=3,column=5)
        Button20=Button(master,text='click me',command=lambda:callback(Button20))
        Button20.grid(row=3,column=6)
        Button21=Button(master,text='click me',command=lambda:callback(Button21))
        Button21.grid(row=3,column=7)
        Button22=Button(master,text='click me',command=lambda:callback(Button22))
        Button22.grid(row=4,column=1)
        Button23=Button(master,text='click me',command=lambda:callback(Button23))
        Button23.grid(row=4,column=2)
        Button24=Button(master,text='click me',command=lambda:callback(Button24))
        Button24.grid(row=4,column=3)
        Button25=Button(master,text='click me',command=lambda:callback(Button25))
        Button25.grid(row=4,column=4)
        Button26=Button(master,text='click me',command=lambda:callback(Button26))
        Button26.grid(row=4,column=5)
        Button27=Button(master,text='click me',command=lambda:callback(Button27))
        Button27.grid(row=4,column=6)
        Button28=Button(master,text='click me',command=lambda:callback(Button28))
        Button28.grid(row=4,column=7)
        Button29=Button(master,text='click me',command=lambda:callback(Button29))
        Button29.grid(row=5,column=1)
        Button30=Button(master,text='click me',command=lambda:callback(Button30))
        Button30.grid(row=5,column=2)
        Button31=Button(master,text='click me',command=lambda:callback(Button31))
        Button31.grid(row=5,column=3)
        Button32=Button(master,text='click me',command=lambda:callback(Button32))
        Button32.grid(row=5,column=4)
        Button33=Button(master,text='click me',command=lambda:callback(Button33))
        Button33.grid(row=5,column=5)
        Button34=Button(master,text='click me',command=lambda:callback(Button34))
        Button34.grid(row=5,column=6)
        Button35=Button(master,text='click me',command=lambda:callback(Button35))
        Button35.grid(row=5,column=7)
        Button36=Button(master,text='click me',command=lambda:callback(Button36))
        Button36.grid(row=6,column=1)
        Button37=Button(master,text='click me',command=lambda:callback(Button37))
        Button37.grid(row=6,column=2)
        Button38=Button(master,text='click me',command=lambda:callback(Button38))
        Button38.grid(row=6,column=3)
        Button39=Button(master,text='click me',command=lambda:callback(Button39))
        Button39.grid(row=6,column=4)
        Button40=Button(master,text='click me',command=lambda:callback(Button40))
        Button40.grid(row=6,column=5)
        Button41=Button(master,text='click me',command=lambda:callback(Button41))
        Button41.grid(row=6,column=6)
        Button42=Button(master,text='click me',command=lambda:callback(Button42))
        Button42.grid(row=6,column=7)
        Button43=Button(master,text='click me',command=lambda:callback(Button43))
        Button43.grid(row=7,column=1)
        Button44=Button(master,text='click me',command=lambda:callback(Button44))
        Button44.grid(row=7,column=2)
        Button45=Button(master,text='click me',command=lambda:callback(Button45))
        Button45.grid(row=7,column=3)
        Button46=Button(master,text='click me',command=lambda:callback(Button46))
        Button46.grid(row=7,column=4)
        Button47=Button(master,text='click me',command=lambda:callback(Button47))
        Button47.grid(row=7,column=5)
        Button48=Button(master,text='click me',command=lambda:callback(Button48))
        Button48.grid(row=7,column=6)
        Button49=Button(master,text='click me',command=lambda:callback(Button49))
        Button49.grid(row=7,column=7)
        Button50=Button(master,text='click me',command=lambda:callback(Button50))
        Button50.grid(row=8,column=1)
        Button51=Button(master,text='click me',command=lambda:callback(Button51))
        Button51.grid(row=8,column=2)
        Button52=Button(master,text='click me',command=lambda:callback(Button52))
        Button52.grid(row=8,column=3)
        Button53=Button(master,text='click me',command=lambda:callback(Button53))
        Button53.grid(row=8,column=4)
        Button54=Button(master,text='click me',command=lambda:callback(Button54))
        Button54.grid(row=8,column=5)
        Button55=Button(master,text='click me',command=lambda:callback(Button55))
        Button55.grid(row=8,column=6)
        Button56=Button(master,text='click me',command=lambda:callback(Button56))
        Button56.grid(row=8,column=7)
        Button57=Button(master,text='click me',command=lambda:callback(Button57))
        Button57.grid(row=9,column=1)
        Button58=Button(master,text='click me',command=lambda:callback(Button58))
        Button58.grid(row=9,column=2)
        Button59=Button(master,text='click me',command=lambda:callback(Button59))
        Button59.grid(row=9,column=3)
        Button60=Button(master,text='click me',command=lambda:callback(Button60))
        Button60.grid(row=9,column=4)
        Button61=Button(master,text='click me',command=lambda:callback(Button61))
        Button61.grid(row=9,column=5)
        Button62=Button(master,text='click me',command=lambda:callback(Button62))
        Button62.grid(row=9,column=6)
        Button63=Button(master,text='click me',command=lambda:callback(Button63))
        Button63.grid(row=9,column=7)
        Button64=Button(master,text='click me',command=lambda:callback(Button64))
        Button64.grid(row=10,column=1)
        Button65=Button(master,text='click me',command=lambda:callback(Button65))
        Button65.grid(row=10,column=2)
        Button66=Button(master,text='click me',command=lambda:callback(Button66))
        Button66.grid(row=10,column=3)
        Button67=Button(master,text='click me',command=lambda:callback(Button67))
        Button67.grid(row=10,column=4)
        Button68=Button(master,text='click me',command=lambda:callback(Button68))
        Button68.grid(row=10,column=5)
        Button69=Button(master,text='click me',command=lambda:callback(Button69))
        Button69.grid(row=10,column=6)
        Button70=Button(master,text='click me',command=lambda:callback(Button70))
        Button70.grid(row=10,column=7)
        Button71=Button(master,text='click me',command=lambda:callback(Button71))
        Button71.grid(row=11,column=1)
        Button72=Button(master,text='click me',command=lambda:callback(Button72))
        Button72.grid(row=11,column=2)
        Button73=Button(master,text='click me',command=lambda:callback(Button73))
        Button73.grid(row=11,column=3)
        Button74=Button(master,text='click me',command=lambda:callback(Button74))
        Button74.grid(row=11,column=4)
        Button75=Button(master,text='click me',command=lambda:callback(Button75))
        Button75.grid(row=11,column=5)
        Button76=Button(master,text='click me',command=lambda:callback(Button76))
        Button76.grid(row=11,column=6)
        Button77=Button(master,text='click me',command=lambda:callback(Button77))
        Button77.grid(row=11,column=7)
        Button78=Button(master,text='click me',command=lambda:callback(Button78))
        Button78.grid(row=12,column=1)
        Button79=Button(master,text='click me',command=lambda:callback(Button79))
        Button79.grid(row=12,column=2)
        Button80=Button(master,text='click me',command=lambda:callback(Button80))
        Button80.grid(row=12,column=3)
        Button81=Button(master,text='click me',command=lambda:callback(Button81))
        Button81.grid(row=12,column=4)
        Button82=Button(master,text='click me',command=lambda:callback(Button82))
        Button82.grid(row=12,column=5)
        Button83=Button(master,text='click me',command=lambda:callback(Button83))
        Button83.grid(row=12,column=6)
        Button84=Button(master,text='click me',command=lambda:callback(Button84))
        Button84.grid(row=12,column=7)
        Button85=Button(master,text='click me',command=lambda:callback(Button85))
        Button85.grid(row=13,column=1)
        Button86=Button(master,text='click me',command=lambda:callback(Button86))
        Button86.grid(row=13,column=2)
        Button87=Button(master,text='click me',command=lambda:callback(Button87))
        Button87.grid(row=13,column=3)
        Button88=Button(master,text='click me',command=lambda:callback(Button88))
        Button88.grid(row=13,column=4)
        Button89=Button(master,text='click me',command=lambda:callback(Button89))
        Button89.grid(row=13,column=5)
        Button90=Button(master,text='click me',command=lambda:callback(Button90))
        Button90.grid(row=13,column=6)
        Button91=Button(master,text='click me',command=lambda:callback(Button91))
        Button91.grid(row=13,column=7)
        Button92=Button(master,text='click me',command=lambda:callback(Button92))
        Button92.grid(row=14,column=1)
        Button93=Button(master,text='click me',command=lambda:callback(Button93))
        Button93.grid(row=14,column=2)
        Button94=Button(master,text='click me',command=lambda:callback(Button94))
        Button94.grid(row=14,column=3)
        Button95=Button(master,text='click me',command=lambda:callback(Button95))
        Button95.grid(row=14,column=4)
        Button96=Button(master,text='click me',command=lambda:callback(Button96))
        Button96.grid(row=14,column=5)
        Button97=Button(master,text='click me',command=lambda:callback(Button97))
        Button97.grid(row=14,column=6)
        Button98=Button(master,text='click me',command=lambda:callback(Button98))
        Button98.grid(row=14,column=7)
        Button99=Button(master,text='click me',command=lambda:callback(Button99))
        Button99.grid(row=15,column=1)
        Button100=Button(master,text='click me',command=lambda:callback(Button100))
        Button100.grid(row=15,column=2)
        Button101=Button(master,text='click me',command=lambda:callback(Button101))
        Button101.grid(row=15,column=3)
        Button102=Button(master,text='click me',command=lambda:callback(Button102))
        Button102.grid(row=15,column=4)
        Button103=Button(master,text='click me',command=lambda:callback(Button103))
        Button103.grid(row=15,column=5)
        Button104=Button(master,text='click me',command=lambda:callback(Button104))
        Button104.grid(row=15,column=6)
        Button105=Button(master,text='click me',command=lambda:callback(Button105))
        Button105.grid(row=15,column=7)


def start_game():
    Admin = Tk()
    Admin.geometry('+650+100')
    app = App(Admin)
    Admin.mainloop()
def adto(chara):
    CharactersA.append(chara)
def select():
    Sel=Tk()
    Dragons=Button(Sel,text="Dragons in our midst Good",command = lambda:adto(diomg))
    DragonsB=Button(Sel,text="Dragons in our Midst Villains",command=lambda:adto(diomb))
    PB=Button(Sel,text="Percy Jackson Bad",command=lambda:adto(pjob))
    PH=Button(Sel,text="Percy Jackson Good",command=lambda:adto(pjog))
    Rng=Button(Sel,text="Rangers Apprentice",command=lambda:adto(RA))
    Drk=Button(Sel,text="Dragon Keeper",command=lambda:adto(dk))
    Psy=Button(Sel,text="Psych",command=lambda:adto(psych))
    Chkg=Button(Sel,text="Chuck Good",command=lambda:adto(chuckg))
    Chkb=Button(Sel,text="Chuck Bad",command=lambda:adto(chuckb))
    Lgd=Button(Sel,text="Legend Of Zelda",command=lambda:adto(LOZ))
    done=Button(Sel,text="DONE",command=start_game)
    KCg=Button(Sel,text="Kensington Chronicles Good",command=lambda:adto(KCG))
    KCb=Button(Sel,text="Kensington Chronicles Bad",command=lambda:adto(KCB))
    KCb.pack()
    KCg.pack()
    Dragons.pack()
    DragonsB.pack()
    PB.pack()
    PH.pack()
    Rng.pack()
    Drk.pack()
    Psy.pack()
    Chkg.pack()
    Chkb.pack()
    Lgd.pack()
    done.pack()
    Sel.geometry('+600+100')
    Sel.mainloop()
select()



